include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
  exclude:
    - lib/**/*.freezed.dart
    - lib/**/*.config.dart
    - lib/**/*.g.dart
    - lib/**/*.graphql.dart
    - lib/presentation/core/translation/i18n.dart

linter:
  rules:
    sort_pub_dependencies: false