targets:
  $default:
    sources:
      - lib/**
      - $package$
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/infrastructure/core/graphql_api.dart
              schema: lib/infrastructure/core/mocsi.schema.graphql
              queries_glob: lib/infrastructure/auth/**.graphql