targets:
  $default:
    sources:
      - lib/**
      - $package$
    builders:
      artemis:
        options:
          custom_parser_import: 'package:mocsi_client/infrastructure/core/graphql/scalar_parsers.dart'
          scalar_mapping:
            - cuse_custom_parser: false
              graphql_type: DateTime
              dart_type: DateTime
            - cuse_custom_parser: true
              graphql_type: Time
              dart_type: DateTime

          schema_mapping:
            - output: lib/infrastructure/auth/graphql_auth_api.dart
              schema: lib/infrastructure/core/graphql/mocsi.schema.graphql
              queries_glob: lib/infrastructure/auth/**.graphql
            - output: lib/infrastructure/rooms/graphql_rooms_api.dart
              schema: lib/infrastructure/core/graphql/mocsi.schema.graphql
              queries_glob: lib/infrastructure/rooms/**.graphql
            - output: lib/infrastructure/conference/graphql_conference_api.dart
              schema: lib/infrastructure/core/graphql/mocsi.schema.graphql
              queries_glob: lib/infrastructure/conference/**.graphql
            - output: lib/infrastructure/profile/graphql_profile_api.dart
              schema: lib/infrastructure/core/graphql/mocsi.schema.graphql
              queries_glob: lib/infrastructure/profile/**.graphql
