targets:
  $default:
    sources:
      - lib/**
      - $package$
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/infrastructure/auth/graphql_auth_api.dart
              schema: lib/infrastructure/core/graphql/mocsi.schema.graphql
              queries_glob: lib/infrastructure/auth/**.graphql
            - output: lib/infrastructure/rooms/graphql_rooms_api.dart
              schema: lib/infrastructure/core/graphql/mocsi.schema.graphql
              queries_glob: lib/infrastructure/rooms/**.graphql
