targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - my.schema.graphql
      - $package$
    builders:
      artemis:
        options:
          shema_mapping:
          - schema: my.schema.graphql
            queries_glob: graphql/**.graphql
            output: lib/graphql/graphql_api.dart
