targets:
  $default:
    sources:
      - lib/**
      - .graphqlconfig
      - $package$
    builders:
      artemis:
        options:
          shema_mapping:
          - schema: lib/infrastructure/core/my.schema.json
            output: lib/infrastructure/core/graphql_api.dart
            queries_glob: lib/**.graphql
