name: mocsi_client
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  flushbar: ^1.10.4
  # Firebase
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.3
  firebase_core: ^1.0.2
  google_sign_in: ^5.0.1
  firebase_crashlytics: ^1.0.0
  firebase_performance: ^0.6.0+1
  # State management
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  # Tools
  uuid: ^3.0.3
  json_annotation: ^4.0.1
  # Auto-gen
  freezed_annotation: ^0.14.1
  get_it: ^6.0.0
  injectable: ^1.2.2
  auto_route: ^1.0.2
  # Functional programming
  dartz: ^0.10.0-nullsafety.1
  kt_dart: ^0.9.0
  rxdart: ^0.26.0
  # Network
  meta: '>=1.0.0 <2.0.0'
  # Translation
  flutter_localizations:
    sdk: flutter



dev_dependencies:
  artemis:
    git:
      url: https://github.com/glynskyi/artemis.git
      ref: c769cb40a8ea0ab856da0c0e5fbdd8e368ed529b
  flappy_translator:
    git:
      url: https://github.com/smartnsoft/FlappyTranslator.git
      ref: feature/null-safety
  lint: ^1.5.3
  # Auto-gen
  freezed: ^0.14.1+1
  injectable_generator: ^1.2.2
  auto_route_generator: ^1.0.2
  json_serializable: ^4.1.0
  # build
  build_runner: ^1.12.2

  flutter_test:
    sdk: flutter

flappy_translator:
  input_file_path: "lib/presentation/core/translation/translation.csv"
  output_dir: "lib/presentation/core/translation"
  file_name: "i18n"
  class_name: "I18n"
  delimiter: ";"
  start_index: 1
  depend_on_context: false
  use_single_quotes: true
  replace_no_break_spaces: false
  expose_get_string: false
  expose_loca_strings: false
  expose_locale_maps: false




flutter:
  assets:
    - assets/logo.png

  uses-material-design: true

