name: mocsi_client
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  # Firebase
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  firebase_core: ^0.5.3
  google_sign_in: ^4.5.6
  # State management
  flutter_bloc: ^6.1.1
  # Tools
  uuid: ^2.2.2
  json_annotation: ^3.1.1
  # Auto-gen
  freezed_annotation: ^0.12.0
  get_it: ^5.0.3
  injectable: ^1.0.5
  auto_route: ^0.6.9
  # Functional programming
  dartz: ^0.9.2
  kt_dart: ^0.8.0
  rxdart: ^0.25.0


dev_dependencies:
  lint: ^1.3.1
  # Auto-gen
  freezed: ^0.12.6
  injectable_generator: ^1.0.6
  auto_route_generator: ^0.6.10
  json_serializable: ^3.5.1
  # build
  build_runner: ^1.10.11
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

