name: mocsi_client
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.0
  # Firebase
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

