name: mocsi_client
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.0
  flushbar: ^1.10.4
  # Firebase
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_core: ^0.7.0
  google_sign_in: ^4.5.9
  # State management
  flutter_bloc: ^6.1.2
  # Tools
  uuid: ^2.2.2
  json_annotation: ^3.1.1
  # Auto-gen
  freezed_annotation: ^0.12.0
  get_it: ^5.0.6
  injectable: ^1.0.7
  auto_route: ^0.6.9
  # Functional programming
  dartz: ^0.9.2
  kt_dart: ^0.8.0
  rxdart: ^0.24.0
  # Network
  graphql_flutter: ^4.0.1
  graphql: ^4.0.1
  # Translation
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flappy_translator: ^1.5.0
  lint: ^1.3.1
  # Auto-gen
  freezed: ^0.12.7
  injectable_generator: ^1.0.7
  auto_route_generator: ^0.6.10
  json_serializable: ^3.5.1
  artemis: ^6.18.4
  # build
  build_runner: ^1.11.1
  flutter_test:
    sdk: flutter


flappy_translator:
  input_file_path: "lib/presentation/core/translation/translation.csv"
  output_dir: "lib/presentation/core/translation"
  file_name: "i18n"
  class_name: "I18n"
  delimiter: ";"
  start_index: 1
  depend_on_context: false
  use_single_quotes: true
  replace_no_break_spaces: false
  expose_get_string: false
  expose_loca_strings: false
  expose_locale_maps: false


flutter:
  assets:
    - assets/logo.png

  uses-material-design: true

