name: mocsi_client
description: A new Flutter application.

publish_to: none

version: 1.1.2+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  another_flushbar: ^1.10.20
  fluttertoast: ^8.0.6
  table_calendar: ^3.0.0
  flutter_launcher_icons: ^0.9.0
  # Firebase
  firebase_auth: ^1.1.1
  cloud_firestore: ^1.0.6
  firebase_core: ^1.0.4
  google_sign_in: ^5.0.2
  firebase_crashlytics: ^2.0.1
  firebase_performance: ^0.7.0+1
  # State management
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  # Tools
  uuid: ^3.0.4
  json_annotation: ^4.0.1
  logger: ^1.0.0
  # Auto-gen
  freezed_annotation: ^0.14.1
  get_it: ^6.1.1
  injectable: ^1.2.2
  auto_route: ^1.0.2
  # Functional programming
  dartz: ^0.10.0-nullsafety.1
  kt_dart: ^0.9.0
  rxdart: ^0.26.0
  # Network
  meta: '>=1.0.0 <2.0.0'
  jitsi_meet: ^4.0.0
  connectivity: ^3.0.3
  # Translation
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # Storage
  flutter_secure_storage: ^4.1.0
  shared_preferences: ^2.0.5



dev_dependencies:
  artemis: ^7.0.0-beta.3
  flappy_translator: ^2.0.0-nullsafety.1
  lint: ^1.5.3
  # Auto-gen
  freezed: ^0.14.1+2
  injectable_generator: ^1.2.2
  auto_route_generator: ^1.0.2
  json_serializable: ^4.1.0
  # build
  build_runner: ^1.12.2

  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

flappy_translator:
  input_file_path: "lib/presentation/core/translation/translation.csv"
  output_dir: "lib/presentation/core/translation"
  file_name: "i18n"
  class_name: "I18n"
  delimiter: ";"
  start_index: 1
  depend_on_context: false
  use_single_quotes: true
  replace_no_break_spaces: false
  expose_get_string: false
  expose_loca_strings: false
  expose_locale_maps: false




flutter:
  assets:
    - assets/app_icon.png
    - assets/mocsi_mascot.png

  uses-material-design: true

